version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timeseries_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data.csv:/app/data.csv
    command: ["sh", "-c", "python load_data.py && uvicorn main:app --host 0.0.0.0 --port 8000"]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: timeseries_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped 